### ISSUE TITLE
 Cannot find module '@babel/runtime/core-js/object/define-property'

### ISSUE THREAD

**Issue by nandawys** [clns/gitlab-cli#15]
Hi, thank you for developing this cli, after install I got this error. Any suggestion?

module.js:549
    throw err;
    ^

Error: Cannot find module '@babel/runtime/core-js/object/define-property'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/git-lab-cli/node_modules/gitlab/dist/es5/index.js:7:30)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by nandawys** [comment]
lab --help
